projects_list:
    path:     /project/list
    defaults: { _controller: RedmineBundle:Redmine:listProject }
    methods: [GET]

project_show:
    path:     /project/{projectId}
    defaults: { _controller: RedmineBundle:Redmine:showProject }
    methods: [GET]
    requirements:
        projectId: '^\d+$'

issues_list:
    path:     /project/{projectId}/issue/list/{page}
    defaults: { _controller: RedmineBundle:Redmine:issuesList, page: 1 }
    methods: [GET]
    requirements:
        projectId: '^\d+$'
        page: '^\d{1,2}$'

issue_show:
    path:     /project/{projectId}/issue/{issueId}
    defaults: { _controller: RedmineBundle:Redmine:showIssue}
    methods: [GET]
    requirements:
        projectId: '^\d+$'
        issueId: '^\d+$'
